config/routes.rb
Rails.application.routes.draw do
  
  # ユーザー情報
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end


  # ホーム画面
  root to: 'users#index'

  # マイページ
  resources :home, only: [:show]

  # 購入画面
  resources :item, only: [:show,] do
    collection do
      get 'index', to: 'item#index'
      post ':id/pay', to: 'item#pay'
      get 'done', to:'item#done'
    end
  end

  resources :card, only: [:index, :new, :create,:destroy,:buy]

  # カテゴリー
  resources :categories,only: [:index,:show]

  # サイズ
  resources :product_sizes,only: :index, defaults: {format: 'json'}
  # 発送方法
  resources :shippingways,only: :index, defaults: {format: 'json'}

  # 出品画面
  resources :listingpage, except: :index 
  post 'listingpage/create', to: 'listingpage#create'
  post 'listingpage/update', to: 'listingpage#update'

  # カテゴリー機能
  namespace :api do
    resources :categories, only: [:index],defaults: {format: 'json'}
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :family_name_kanji, :last_name_kanji, :family_name_kana, :last_name_kana,
    format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'は全角で入力して下さい。'}
  validates :nickname, :birthday, presence: true
  has_one :address
  has_many :products
  has_many :credits
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @products = Product.order('products.created_at desc').limit(3)
  end
end

app/helpers/users_helper.rb
module UsersHelper  
end

app/views/users/_footer.html.haml
-# footer
.footer
  %ul.contents
    %li.content
      %h2.content__head FURIMAについて
      %ul.content__main
        %li
          =link_to "会社概要（運営会社）"
        %li
          =link_to "プライバシーポリシー"
        %li
          =link_to "FURIMA利用規約"
        %li
          =link_to "ポイントに関する特約"
    %li.content
      %h2.content__head FURIMAを見る
      %ul.content__main
        %li
          =link_to "カテゴリー一覧"
        %li
          =link_to "ブランド一覧"
    %li.content
      %h2.content__head ヘルプ＆ガイド
      %ul.content__main
        %li
          =link_to "FURIMAガイド"
        %li
          =link_to "FURIMAロゴ利用ガイドライン"
        %li
          =link_to "お知らせ"
  .footer__logo
    = link_to "/", class:"top" do
      =image_tag 'logos/logo-white.png'
  %p © FURIMA

app/views/users/_header.html.haml
-# header
.header
  .header__headerInner
    -# 検索bar
    .header__headerInner__mainHeader
      = link_to image_tag("logos/logo.png", alt: "サンプル画像"), root_path
      
      .header__headerInner__mainHeader__search
        %input{type: "text",placeholder: 'キーワードから探す'}
        %button{type: "submit"}
          =fa_icon 'search', class: 'header__headerInner__mainHeader__search__icon'
          
    -# ナビbar
    .header__headerInner__nav
      %ul.header__headerInner__nav__left
        %li= link_to 'カテゴリー','#', class: 'header__headerInner__nav__left__categories'
        %li= link_to 'ブランド','#', class: 'header__headerInner__nav__left__brand'

      %ul.header__headerInner__nav__right
        - if user_signed_in?
          = link_to "ログアウト", destroy_user_session_path, method: :delete,class:'header__headerInner__nav__right__left'
          -# 実際の記述
          = link_to "マイページ" ,home_path(current_user.id)
        - else
          %li.header__headerInner__nav__right__login= link_to "新規登録", new_user_registration_path
          = link_to "ログイン", new_user_session_path

app/views/users/index.html.haml
-# 最初のページ
= render "header"
.main
  .auction
    .auction__button
      - if user_signed_in?
        = link_to new_listingpage_path, class: 'auction', target: '_self' do
          .action__button__head 出品する
          %i.fas.fa-camera
      - else
        = link_to new_user_registration_path, class: 'auction', target: '_self' do
          .action__button__head 出品する
          %i.fas.fa-camera
    
  .furima
    = image_tag 'logos/picture1.jpg', class: 'picture1'
    .furima__copy
      人生を変えるフリマアプリ
    .furima__copy2
      FURIMAはだれでもかんたんに出品・購入できる</p>フリマアプリです。
      .furima__download
        = link_to "http://www.google.co.jp", class:"apple__btn" do
          = image_tag 'logos/applelogo.png', class: 'applelogo'
        = link_to "http://www.google.co.jp", class:"google__btn" do
          = image_tag 'logos/googlelogo.png', class: 'googlelogo'
  .furima2
    .furima-use
      .furima-point
        FURIMAが選ばれる３つの理由
    .furima-reason
      .furima-reason__pic1
        =image_tag 'logos/pict-reason-01.jpg', class: 'reason1'
        .furima-reason__namber1
          1
      .furima-reason__pic2
        =image_tag 'logos/pict-reason-02.jpg', class: 'reason1'
        .furima-reason__namber2
          2
      .furima-reason__pic3
        =image_tag 'logos/pict-reason-03.jpg', class: 'reason1'
        .furima-reason__namber3
          3
    .furima-catch
      .furima-catch__copy
        %span 3分 
        ですぐに出品
      .furima-catch__copy2
        %span シンプル
        で使いやすい
      .furima-catch__copy3
        手数料 
        %span 業界最安
    .furima-description
      .furima-description__1
        スマホで入力するだけで簡単に出品で
        %p きる！
      .furima-description__2
        めんどくさい入力は必要なく、検索も
        %p 購入もスムーズ！
      .furima-description__3
        最大３％でお得に出品＆＆購入！

  .furima3
    = image_tag 'logos/picture2.jpg', class: 'picture2'
    .furima3__copy
      会員数日本一位
    .furima3__copy2
      FURIMAは、フリマアプリで最も人気。</p>出品・購入回数も業界最多です！</p>ほしかったあの商品に出会えるかもしれません。
      .furima3__download
        = link_to "http://www.google.co.jp", class:"apple__btn" do
          = image_tag 'logos/applelogo.png', class: 'applelogo2'
        = link_to "http://www.google.co.jp", class:"google__btn" do
          = image_tag 'logos/googlelogo.png', class: 'googlelogo2'

  .furima4
    .furima4-use
      .furima4-point
        FURIMAの特徴
      .furima-reason2
        .furima4-reason__pic1
          =image_tag 'logos/icon-01.png', class: 'reason2'
        .furima4-reason__pic2
          =image_tag 'logos/icon-03.png', class: 'reason2'
        .furima4-reason__pic3
          =image_tag 'logos/icon-04.png', class: 'reason2'
    .furima4-catch
      .furima4-catch__copy1
        簡単に売り買い出来る
      .furima4-catch__copy2
        売上金は即日振込振込みに対応
      .furima4-catch__copy3
        様々な支払いに対応
    .furima4-description
      .furima4-description__1
        スマホひとつで、いつでもどこでも簡単
        %p に出品・購入が可能！
      .furima4-description__2
        午前9時までに振込を依頼いただけれ
        %p ば、翌日に指定の口座に入金いたします！
      .furima4-description__3
        お支払いは、クレジットカードだけでな
        %p く、ポイントや売上金など多彩な方法が
        %p あります。
    
  .furima5
    .furima5__category
      ピックアップカテゴリー
    .furima5__item
      新規投稿商品
    .furima5__picture
      -@products.each do |item|
        = link_to listingpage_path(item.id),class:'furima5__picture__list' do
          .list1= image_tag item.images.first.src.url,width:'100%',height:'200px'
          .list2= item.title
          .list3= item.price
          -if item.purchaser_id.present?
            .item_sold_index
              sold
      

    .furima5-brand
      ピックアップブランド
    .furima5-item2
      アーカイブ

  
  .furima6
    =image_tag 'logos/picture3.jpg', class: 'picture3'
    .furima6-copy
      だれでもかんたん、人生を変えるフリマアプリ
    .furima6-copy2
      今すぐ無料ダウンロード！
      .furima6-download
        = link_to "http://www.google.co.jp", class:"apple__btn" do
          = image_tag 'logos/applelogo.png', class: 'applelogo3'
        = link_to "http://www.google.co.jp", class:"google__btn" do
          = image_tag 'logos/googlelogo.png', class: 'googlelogo3'

= render 'footer'