config/routes.rb
Rails.application.routes.draw do
  
  # ユーザー情報
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end


  # ホーム画面
  root to: 'users#index'

  # マイページ
  resources :home, only: [:show]

  # 購入画面
  resources :item, only: [:show,] do
    collection do
      get 'index', to: 'item#index'
      post ':id/pay', to: 'item#pay'
      get 'done', to:'item#done'
    end
  end

  resources :card, only: [:index, :new, :create,:destroy,:buy]

  # カテゴリー
  resources :categories,only: [:index,:show]

  # サイズ
  resources :product_sizes,only: :index, defaults: {format: 'json'}
  # 発送方法
  resources :shippingways,only: :index, defaults: {format: 'json'}

  # 出品画面
  resources :listingpage, except: :index 
  post 'listingpage/create', to: 'listingpage#create'
  post 'listingpage/update', to: 'listingpage#update'

  # カテゴリー機能
  namespace :api do
    resources :categories, only: [:index],defaults: {format: 'json'}
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_home, only: [:show]
  before_action :correct_user, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  private


  def set_home
    @user = User.find(params[:id])
  end

  def correct_user
    unless  user_signed_in? && current_user.id==@user.id
      redirect_to root_path,notice:"自分意外のマイページを表示することはできません。"
    end
  end
end

app/views/home/show.html.haml
= render "users/header"
%body
.main2
  .main2__left
    .main2__left2
      %ul.setting
        %li= link_to 'マイページ', '#'
        %li= link_to 'お知らせ', '#'
        %li= link_to 'やることリスト', '#'
        %li= link_to 'いいね！一覧', '#'
        %li= link_to '出品する', '#'
        %li= link_to '出品した商品 - 出品中', '#'
        %li= link_to '出品した商品 - 取引中', '#'
        %li= link_to '出品した商品 - 売却済み', '#'
        %li= link_to '購入した商品 - 取引中', '#'
        %li= link_to '購入した商品 - 過去の取引', '#'
        %li= link_to 'ニュース一覧', '#'
        %li= link_to '評価一覧', '#'
        %li= link_to 'ガイド', '#'
        %li= link_to 'お問い合わせ', '#', class:'got'
        %h3.topic メルペイ
      %ul.setted
        %li= link_to '残高・振り込み申請','#'
        %li= link_to 'ポイント', '#',class: 'get'
        %h3.setting 設定
      %ul.set
        %li= link_to 'プロフィール','#'
        %li= link_to '発送元・お届け先住所変更','#'
        %li= link_to '支払い方法',new_card_path,method: :get
        %li= link_to 'メール/パスワード','#'
        %li= link_to '本人情報','#'
        %li= link_to '電話番号の確認','#'
        %li= link_to 'ログアウト','#', class: 'git'
  .main__right
    %section.into_box
      = link_to "#" do
        = image_tag 'logos/donald.jpg', class: 'person'
        %h2.my_name= @user.nickname
        .longer
          .evaluation 評価
          %span.number 44
          .count 出品数
          %span.number2 38
    %section.covers
      %ul.tab
        %li.active
          %h3.left_tab= link_to 'お知らせ'
        %li.todo
          %h3.right_tab= link_to 'やることリスト'
      .tab_content
        %ul.tab_menu.active
          %li
            = link_to "#" do
              %figure.tom
                = image_tag 'logos/LtXe7958_400x400.jpg', class: 'others'
              .ground
                .in_content ヒロさん、他１２名が「ドラゴンボール」にいいねしました
                %time
                  =fa_icon 'clock', class: 'hours'
                  %span.timer 10時間前
          %li
            = link_to "#" do
              %figure.tom
                = image_tag 'logos/LtXe7958_400x400.jpg', class: 'others'
              .ground
                .in_content ヒロさん、他１２名が「ドラゴンボール」にいいねしました
                %time 
                  =fa_icon 'clock', class: 'hours'
                  %span.timer 10時間前
          %li
            = link_to "#" do
              %figure.tom
                = image_tag 'logos/LtXe7958_400x400.jpg', class: 'others'
              .ground
                .in_content ヒロさん、他１２名が「ドラゴンボール」にいいねしました
                %time 
                  =fa_icon 'clock', class: 'hours'
                  %span.timer 10時間前
          %li.last_tab
            = link_to "一覧を見る" 
    %section.bottom_tab
      %h2.bought 購入した商品
      %ul.deals
        %li.activo 
          %h3.deal=link_to '取引中' 
        %li.vel
          %h3.ago=link_to '過去の取引'
      .bomber  
        %ul.lister
          %li.buy_one
            = link_to "#" do
              %figure.user_inner
                = image_tag 'logos/LtXe7958_400x400.jpg', class: 'user_image'
              .ground
                .in_content 「ドラゴンボール」を購入しました。受取評価をしました。
                .out_content 評価待ち
          %li.last_one
            = link_to "一覧を見る" 
= render "users/footer"