config/routes.rb
Rails.application.routes.draw do
  
  # ユーザー情報
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end


  # ホーム画面
  root to: 'users#index'

  # マイページ
  resources :home, only: [:show]

  # 購入画面
  resources :item, only: [:show,] do
    collection do
      get 'index', to: 'item#index'
      post ':id/pay', to: 'item#pay'
      get 'done', to:'item#done'
    end
  end

  resources :card, only: [:index, :new, :create,:destroy,:buy]

  # カテゴリー
  resources :categories,only: [:index,:show]

  # サイズ
  resources :product_sizes,only: :index, defaults: {format: 'json'}
  # 発送方法
  resources :shippingways,only: :index, defaults: {format: 'json'}

  # 出品画面
  resources :listingpage, except: :index 
  post 'listingpage/create', to: 'listingpage#create'
  post 'listingpage/update', to: 'listingpage#update'

  # カテゴリー機能
  namespace :api do
    resources :categories, only: [:index],defaults: {format: 'json'}
  end

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"
  before_action :set_card, except: [:index,:new,:create,:destroy]

  def index
   @card = Card.where(user_id: current_user.id).first

    if @card.present?
      Payjp.api_key = Rails.application.credentials.payjp[:private_key]
      customer = Payjp::Customer.retrieve(@card.payjp_id)
      @card_info = customer.cards.retrieve(customer.default_card)
      @card_brand = @card_info.brand
      @exp_month = @card_info.exp_month.to_s
      @exp_year = @card_info.exp_year.to_s.slice(2,3) 

      case @card_brand
      when "Visa"
        @card_image = "visa.png"
      when "JCB"
        @card_image = "jcb.png"
      when "MasterCard"
        @card_image = "master-card.png"
      when "American Express"
        @card_image = "american_express.png"
      when "Diners Club"
        @card_image = "dinersclub.png"
      when "Discover"
        @card_image = "discover.png"
      end
    else  
     render "new"
    end
  end

  def new
    # @card = Card.new
    @card = Card.where(user_id: current_user.id).first
     redirect_to action: "index" if @card.present?    
  end

  def create
    # Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    Payjp.api_key = Rails.application.credentials.payjp[:private_key]
    if params['payjpToken'].blank?
      render "new"
    else
      customer = Payjp::Customer.create(
        description: 'test',
        email: current_user.email,
        card: params['payjpToken'],
        metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, payjp_id: customer.id)
      if @card.save!
        # if request.referer&.include?("/registrations/step5")
        #   redirect_to controller: 'registrations', action: "step6"
        # else
        #   redirect_to url:"card_index_path",method: :post, notice:"支払い情報の登録が完了しました"
        # end
      else
        render 'new'
      end
    end
  end


 def destroy
   
   @card = Card.where(user_id: current_user.id).first

   Payjp.api_key = Rails.application.credentials.payjp[:private_key]
   customer = Payjp::Customer.retrieve(@card.payjp_id)
   customer.delete
   if @card.destroy
    render 'destroy', notice: "削除しました"
   else
    redirect_to action: "index", alert: "削除できませんでした"
   end
  end


  private

  def set_card
     @card = Card.find(params[:id])
      # @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end
end

app/views/card/create.html.haml
= render "users/header"

%main
  %section.container
    %h2.container__message 登録が完了しました
    = link_to "トップへ戻る", root_path

app/views/card/destroy.html.haml
= render "users/header"

%main
  %section.container
    %h2.container__message 削除が完了しました
    = link_to "トップへ戻る", root_path

app/views/card/index.html.haml
= render "users/header"

%main
  %section.container
    %h2.container__message クレジットカード情報
    .container__main
      .card_namber
      = "**** **** **** " + @card_info.last4
      .card_period
      = @exp_month + " / " + @exp_year
      = @card_brand
      .card_brand
      = image_tag "logos/#{@card_image}"
      .card_delete
      = link_to "削除する",card_path(@card.id),method: "delete"
      

= render "users/footer"

app/views/card/new.html.haml
= render "users/header"

%main
  %section.container
    %h2.container__message クレジットカード情報登録
    .container__main
      .account-page__inner--right.user-form
        = form_with url:card_index_path ,method: :post, local: true, id: "charge-form" do |f|
          .field
            = f.label :card_namber,"クレジット番号"
            %br/
            = f.text_field :card_number, :placeholder => "半角数字のみ"
          .field
            = f.label :cvc,"セキュリティーコード"
            %br/
            = f.password_field :cvc, autocomplete: "security_code", :placeholder => "カード背面3,4桁の番号"
          .field
            = f.label :expiration_data,"有効期限"
            %br/
            = f.select :exp_month, ['1','2','3','4','5','6','7','8','9','10','11','12'],{include_blank: ''}
            %span 月/
            = f.select :exp_year, ['2020','2021','2022','2023','2024','2025','2026','2027','2028','2029','2030'],{include_blank: ''}
            %span 年
          .field
            = f.label :account_holder,"口座名義"
            %br/
            = f.text_field :account_holder, :placeholder => "（例：YOHEI KAWASE）"
          .actions
            = f.submit "登録する", id: "charge-submit"

= render "users/footer"